### ISSUE TITLE
When does an order expire?

### ISSUE THREAD

**Issue by nahtnam** [snitko/straight-server#8]
Hey!

I was wondering after how long a order expires.

Thanks.

**Comment by snitko** [comment]
I've just made the following two commits which should answer your question:

https://github.com/snitko/straight/commit/1c39c4cad551eb3c590ff918862a399b8f120fb3
https://github.com/snitko/straight-server/commit/3bf44225f0efd9dacf483ca88f0eeb34040d667f

Basically, you now have a field `Gateway#orders_expiration_period` where you can state in seconds how long before an Order for this gateway can be considered expired. This is when it stops checking for new transactions. If you're using a config file, you can simply add `orders_expiration_period: 900` line to your gateways config, which says all orders for this gateway expire in 15 minutes (900 seconds). If you're using a DB for storing gateway info, there's now a corresponding field in the DB too.

Bear in mind that this feature is covered by adding code into two gems, both `straight` and `straight-server` and the respective code in `straight-server` relies on changes in `straight`. Until there is a release, you'd have to manually build and install them. At this point, if you only build and install an edge version of `straight-server`, but not `straight`, it won't work.

**Comment by nahtnam** [comment]
@snitko Ok, thanks for the update! :)
